### ISSUE TITLE
请问这个除了数据集，其他代码部分会继续开源吗

### ISSUE THREAD

**Issue by sunmin123456** [pynsigrid/Vibration-Detection#2]

**Comment by Jiangyuxin11** [comment]
下载数据集后有碰到图片打不开的情况吗

**Comment by qeg123** [comment]
> 下载数据集后有碰到图片打不开的情况吗

大佬，这个数据集下载后我也打不开，请问这个问题你解决了吗？

**Comment by Jiangyuxin11** [comment]
> > 下载数据集后有碰到图片打不开的情况吗
> 
> 大佬，这个数据集下载后我也打不开，请问这个问题你解决了吗？

没有呢 现在网页上图片都不显示了
